site_name: Hands-on with the ORCID API
theme: material
extra_css: 
    - css/theme_override.css
extra:
  palette:
    primary: 'grey'
  font:
    text: 'Noto Sans'
  logo: 'images/id-icon.svg' 
pages:
    - 1. Introduction: index.md
    - 2. Accessing ORCID APIs: access.md
    - 2. Set up the Sandbox: sandbox.md
    - 3. READ public info: read.md
    - 4. SEARCH public info: search.md
    - 5. AUTHENTICATE iDs: authenticate.md
    - 6. ADD information: add.md
    - 7. UPDATE information: update.md
    - 8. Resources: resources.md